version: '3.8'

services:
  gitlab:
    container_name: gitlab-ce
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    profiles: [gitlab]
    hostname: gitlablocal.dev
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlablocal.dev'
        gitlab_rails['gitlab_shell_ssh_port'] = 1022
    ports:
      - "80:80"
      - "443:443"
      - "1022:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    networks:
      gitprovider:
        ipv4_address: 10.5.0.5
    healthcheck:
      test: ["CMD", "/opt/gitlab/bin/gitlab-healthcheck", "--fail", "--max-time", "10"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s

  runner:
    image: gitlab/gitlab-runner:alpine
    profiles: [gitlab]
    restart: unless-stopped
    container_name: gitlab-runner
    hostname: gitlab-runner.dev
    depends_on:
      gitlab:
        condition: service_healthy
    volumes:
      - ./config/gitlab-runner:/etc/gitlab-runner
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
    networks:
      gitprovider:
        ipv4_address: 10.5.0.6

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    profiles: [gitea]
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD:-gitea}
    restart: unless-stopped
    networks:
      gitprovider:
        ipv4_address: 10.5.0.7
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/sbin/nginx", "-t"]
      interval: 60s
      timeout: 10s
      retries: 3

  db:
    image: postgres:16-alpine
    profiles: [gitea]
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${GITEA_DB_PASSWORD:-gitea}
      - POSTGRES_DB=gitea
    networks:
      gitprovider:
        ipv4_address: 10.5.0.8
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gitea"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  gitprovider:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
